version: 2

sources:

  - name: axis_core
    database: dbt
    tables: 
      - name: walletprofiles

  - name: axis_kyc
    database: dbt
    tables:
      - name: partner

  - name: dbt-dimensions
    tables:
      - name: profiles_stagging
      - name: profiles_stagging_2
      - name: profiles_dimension